# CI de Nível 01
name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

  e2e-tests:
    runs-on: ['ubuntu-latest']
    needs: [inspection]
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Cypress
        run: yarn cypress install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      # passed, faled, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./cypress/reports/html
          